// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbopzdisomurujaddqpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZib3B6ZGlzb211cnVqYWRkcXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTc5NjgsImV4cCI6MjA2NTU5Mzk2OH0.7av4hDCN1ytrLftX0LFElKKA9tQtp2Clkww9U9Lvyz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);